services:
  redis:
      image: "redis:latest"
      ports:
        - "6379:6379"
      restart: on-failure
  backend-api:
    image: "pulkitkakar/my-chat:1.0"
    ports:
      - "3001:3001"
    pull_policy: always
    depends_on:
      - redis
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://root:my-secret-pw@localhost:3306/mychatdb